"""Tests for posterior inference over proxy parameters.

The load-bearing test is :class:`TestGradient` — a hand-derived gradient that is
subtly wrong still produces a smooth, plausible-looking posterior centred on the
wrong place, and nothing downstream would catch it. Everything else checks that
the sampler is honest about its own failures.
"""

from __future__ import annotations

import numpy as np
import pytest
from scipy import stats

from beta_swarm.agents import Archetype
from beta_swarm.inference import hmc
from beta_swarm.inference.proxy_posterior import (
    N_PARAMS,
    ProxyPosterior,
    ProxyTheta,
    design_from_observables,
    natural_draws,
)
from beta_swarm.proxy import BetaProxyComputer


# ----------------------------------------------------------------------
# Fixtures
# ----------------------------------------------------------------------
def _synthetic_design(n=400, seed=0, theta=None):
    """Draw observables from the archetype emission model, outcomes from `theta`.

    Outcomes are generated by the *model being fitted*, so parameter recovery is
    a real test of the estimator rather than of model misspecification.
    """
    rng = np.random.default_rng(seed)
    from beta_swarm.agents import SimAgent

    agents = [SimAgent.make(a.value, a) for a in (Archetype.HONEST, Archetype.MEDIOCRE)]
    obs_list, latent = [], []
    for _ in range(n):
        agent = agents[rng.integers(len(agents))]
        v = agent.sample_outcome(rng)
        obs_list.append(agent.emit_observables(v, rng))
        latent.append(v)

    if theta is None:
        return obs_list, latent

    proxy = theta.to_proxy()
    outcomes = [float(proxy.compute_belief(o).sample(rng)) for o in obs_list]
    return obs_list, outcomes


@pytest.fixture(scope="module")
def design():
    obs, outcomes = _synthetic_design(n=300, seed=1)
    return design_from_observables(obs, outcomes)


# ----------------------------------------------------------------------
class TestDesign:
    def test_features_match_the_proxy(self, design):
        """The design must reproduce `compute_v_hat` for uniform weights."""
        obs, _ = _synthetic_design(n=20, seed=7)
        d = design_from_observables(obs, [0.5] * 20)
        proxy = BetaProxyComputer(
            w_progress=0.25, w_rework=0.25, w_verifier=0.25, w_engagement=0.25
        )
        expected = [proxy.compute_v_hat(o) for o in obs]
        got = d.features @ np.full(4, 0.25)
        np.testing.assert_allclose(got, expected, rtol=1e-12, atol=1e-12)

    def test_evidence_matches_the_proxy(self):
        obs, _ = _synthetic_design(n=20, seed=8)
        d = design_from_observables(obs, [0.5] * 20)
        proxy = BetaProxyComputer(base_concentration=2.0, evidence_scale=1.0)
        expected = [proxy.compute_concentration(o) - 2.0 for o in obs]
        np.testing.assert_allclose(d.evidence, expected, rtol=1e-12)

    def test_boundary_outcomes_are_counted_not_swallowed(self):
        obs, _ = _synthetic_design(n=4, seed=3)
        d = design_from_observables(obs, [0.0, 1.0, 0.5, 0.25])
        assert d.n_clamped == 2
        assert np.all(d.outcomes > 0.0) and np.all(d.outcomes < 1.0)

    def test_out_of_range_outcomes_rejected(self):
        obs, _ = _synthetic_design(n=2, seed=3)
        with pytest.raises(ValueError, match="outcomes must lie"):
            design_from_observables(obs, [1.5, 0.5])

    def test_clip_in_compute_v_hat_never_binds(self, design):
        """The simplex parameterization relies on this; assert it, don't assume."""
        assert np.all(np.abs(design.features) <= 1.0 + 1e-12)
        for w in np.random.default_rng(0).dirichlet(np.ones(4), size=50):
            v_hat = design.features @ w
            assert np.all(np.abs(v_hat) <= 1.0 + 1e-12)


class TestTheta:
    def test_round_trip_through_proxy(self):
        u = np.array([0.3, -0.7, 0.2, np.log(2.5), np.log(3.0), np.log(1.2)])
        theta = ProxyTheta.from_vector(u)
        assert theta.sigmoid_k == pytest.approx(2.5)
        assert theta.base_concentration == pytest.approx(3.0)
        assert theta.evidence_scale == pytest.approx(1.2)
        assert theta.w.sum() == pytest.approx(1.0)
        proxy = theta.to_proxy()
        # BetaProxyComputer renormalizes; a simplex vector must survive that.
        np.testing.assert_allclose(proxy._w, theta.w, rtol=1e-12)

    def test_weights_identified_up_to_the_pinned_logit(self):
        """Shifting all logits leaves w unchanged — the redundancy we removed."""
        base = ProxyTheta.from_vector(np.array([0.0, 0.0, 0.0, 0.0, 0.0, 0.0]))
        np.testing.assert_allclose(base.w, np.full(4, 0.25), rtol=1e-12)


# ----------------------------------------------------------------------
class TestGradient:
    """The analytic gradient against central finite differences.

    If this fails, every posterior in this package is wrong.
    """

    @pytest.mark.parametrize("seed", [0, 1, 2, 3, 4])
    def test_matches_finite_differences(self, design, seed):
        rng = np.random.default_rng(seed)
        post = ProxyPosterior(design)
        u = post.prior_mean + rng.normal(scale=0.4, size=N_PARAMS)

        value, grad = post.log_prob_and_grad(u)
        assert np.isfinite(value)

        eps = 1e-6
        numeric = np.empty(N_PARAMS)
        for j in range(N_PARAMS):
            up, dn = u.copy(), u.copy()
            up[j] += eps
            dn[j] -= eps
            numeric[j] = (post.log_prob(up) - post.log_prob(dn)) / (2 * eps)

        np.testing.assert_allclose(grad, numeric, rtol=2e-5, atol=2e-5)

    def test_value_agrees_with_direct_beta_logpdf(self, design):
        """The likelihood must be the Beta density the proxy actually produces."""
        u = np.array([0.2, -0.3, 0.1, np.log(2.0), np.log(2.0), np.log(1.5)])
        post = ProxyPosterior(design)
        proxy = ProxyTheta.from_vector(u).to_proxy()

        total = 0.0
        for i in range(len(design)):
            mean = 1.0 / (1.0 + np.exp(-proxy.sigmoid_k * (design.features[i] @ proxy._w)))
            conc = proxy.base_concentration + proxy.evidence_scale * design.evidence[i]
            total += stats.beta.logpdf(design.outcomes[i], mean * conc, (1 - mean) * conc)
        prior = -0.5 * np.sum(((u - post.prior_mean) / post.prior_sd) ** 2)

        assert post.log_prob(u) == pytest.approx(total + prior, rel=1e-10)

    def test_gradient_is_zero_at_an_interior_optimum(self, design):
        """Gradient ascent must reach a point the analytic gradient calls flat."""
        post = ProxyPosterior(design)
        u = post.init_point()
        for _ in range(4000):
            _, g = post.log_prob_and_grad(u)
            u = u + 1e-4 * g
        _, g = post.log_prob_and_grad(u)
        assert np.max(np.abs(g)) < 1e-2 * len(design)


# ----------------------------------------------------------------------
class TestSampler:
    def test_recovers_a_correlated_gaussian(self):
        """A target whose answer is known in closed form."""
        cov = np.array([[1.0, 0.85], [0.85, 1.4]])
        prec = np.linalg.inv(cov)

        def logp_and_grad(q):
            g = -prec @ q
            return float(-0.5 * q @ prec @ q), g

        res = hmc.sample(
            logp_and_grad, init=np.zeros(2),
            n_draws=1500, n_warmup=1000, n_chains=4, seed=11,
        )
        assert res.diagnostics.divergences == 0
        assert np.all(res.diagnostics.rhat < 1.01)
        np.testing.assert_allclose(res.mean(), np.zeros(2), atol=0.08)
        np.testing.assert_allclose(np.cov(res.flat.T), cov, atol=0.12)

    def test_step_size_adapts_toward_target(self):
        def logp_and_grad(q):
            return float(-0.5 * q @ q), -q

        res = hmc.sample(
            logp_and_grad, init=np.zeros(3),
            n_draws=600, n_warmup=600, n_chains=2, seed=5, target_accept=0.8,
        )
        for rate in res.diagnostics.accept_rate:
            assert 0.6 < rate < 0.95

    def test_rejects_non_finite_start(self):
        def logp_and_grad(q):
            return -np.inf, np.zeros_like(q)

        with pytest.raises(ValueError, match="initial log density"):
            hmc.sample(logp_and_grad, init=np.zeros(2), n_draws=10, n_warmup=10)

    def test_chain_count_mismatch_rejected(self):
        def logp_and_grad(q):
            return float(-0.5 * q @ q), -q

        with pytest.raises(ValueError, match="n_chains"):
            hmc.sample(
                logp_and_grad, init=np.zeros((3, 2)),
                n_draws=10, n_warmup=10, n_chains=4,
            )


class TestDiagnosticsCanFail:
    """A diagnostic that cannot fire is decoration. These make each one fire."""

    def test_funnel_produces_divergences(self):
        """Neal's funnel: curvature no fixed step size can track.

        Betancourt's central example. The sampler must *report* the failure
        rather than return clean-looking draws from the funnel's mouth.
        """
        def logp_and_grad(q):
            v, x = q[0], q[1:]
            if abs(v) > 30:
                return -np.inf, np.zeros_like(q)
            logp = -0.5 * (v / 3.0) ** 2 - 0.5 * np.sum(x**2) * np.exp(-v) - 4.5 * v
            gv = -v / 9.0 + 0.5 * np.sum(x**2) * np.exp(-v) - 4.5
            gx = -x * np.exp(-v)
            return float(logp), np.concatenate([[gv], gx])

        res = hmc.sample(
            logp_and_grad, init=np.zeros(10),
            n_draws=600, n_warmup=600, n_chains=2, seed=3, target_accept=0.8,
        )
        d = res.diagnostics
        assert d.divergences > 0, "funnel must produce divergences"
        assert any("divergent" in w for w in d.warnings())

    def test_rhat_detects_disagreeing_chains(self):
        """Two well-separated modes, chains started in each, must not look mixed."""
        def logp_and_grad(q):
            # Mixture of two sharp Gaussians at -8 and +8; the barrier between
            # them is far too high for any chain to cross.
            a, b = q - 8.0, q + 8.0
            la = -0.5 * np.sum(a**2)
            lb = -0.5 * np.sum(b**2)
            m = max(la, lb)
            tot = m + np.log(np.exp(la - m) + np.exp(lb - m))
            wa = np.exp(la - m) / (np.exp(la - m) + np.exp(lb - m))
            return float(tot), -(wa * a + (1 - wa) * b)

        inits = np.array([[-8.0], [8.0], [-8.0], [8.0]])
        res = hmc.sample(
            logp_and_grad, init=inits,
            n_draws=500, n_warmup=500, n_chains=4, seed=2,
        )
        assert res.diagnostics.rhat[0] > 1.01
        assert any("R-hat" in w for w in res.diagnostics.warnings())

    def test_clean_run_reports_no_warnings(self):
        def logp_and_grad(q):
            return float(-0.5 * q @ q), -q

        res = hmc.sample(
            logp_and_grad, init=np.zeros(2),
            n_draws=1500, n_warmup=1000, n_chains=4, seed=9,
        )
        assert res.diagnostics.warnings() == []
        assert "OK" in res.diagnostics.summary()


class TestDiagnosticFunctions:
    def test_rhat_near_one_for_iid_draws(self):
        rng = np.random.default_rng(0)
        draws = rng.normal(size=(4, 2000, 3))
        assert np.all(hmc.split_rhat(draws) < 1.01)

    def test_ess_near_n_for_iid_draws(self):
        rng = np.random.default_rng(0)
        draws = rng.normal(size=(4, 2000, 2))
        ess = hmc.effective_sample_size(draws)
        assert np.all(ess > 0.7 * 8000)

    def test_ess_drops_for_correlated_draws(self):
        rng = np.random.default_rng(0)
        x = np.zeros((4, 2000, 1))
        for c in range(4):
            for t in range(1, 2000):
                x[c, t, 0] = 0.95 * x[c, t - 1, 0] + rng.normal()
        assert hmc.effective_sample_size(x)[0] < 0.15 * 8000

    def test_constant_parameter_reports_nan_not_one(self):
        """A frozen coordinate is un-converged, not perfectly converged."""
        draws = np.ones((4, 100, 1))
        assert np.isnan(hmc.split_rhat(draws)[0])

    def test_ebfmi_is_low_for_a_slowly_drifting_energy(self):
        slow = np.cumsum(np.random.default_rng(0).normal(size=2000)) * 0.1
        assert hmc.ebfmi(slow) < 0.3
        fast = np.random.default_rng(0).normal(size=2000)
        assert hmc.ebfmi(fast) > 1.0


# ----------------------------------------------------------------------
class TestParameterRecovery:
    """End to end: simulate from known parameters, confirm the posterior covers them."""

    def test_posterior_covers_the_truth(self):
        truth = ProxyTheta(
            w=np.array([0.5, 0.2, 0.2, 0.1]),
            sigmoid_k=2.5,
            base_concentration=3.0,
            evidence_scale=1.2,
        )
        obs, outcomes = _synthetic_design(n=1500, seed=4, theta=truth)
        post = ProxyPosterior(design_from_observables(obs, outcomes))

        rng = np.random.default_rng(0)
        res = hmc.sample(
            post, init=post.dispersed_inits(4, rng),
            n_draws=600, n_warmup=600, n_chains=4, seed=17,
        )
        assert res.diagnostics.divergences == 0, res.diagnostics.summary()
        assert np.all(res.diagnostics.rhat < 1.02), res.diagnostics.summary()

        nat = natural_draws(res.draws)
        lo, hi = np.quantile(nat.reshape(-1, nat.shape[-1]), [0.005, 0.995], axis=0)
        true_vec = truth.to_vector()
        covered = (lo <= true_vec) & (true_vec <= hi)
        # 99% marginal intervals on 7 parameters: allow one miss to noise.
        assert covered.sum() >= 6, (
            f"only {covered.sum()}/7 covered\n"
            f"truth={np.round(true_vec, 3)}\nlo={np.round(lo, 3)}\nhi={np.round(hi, 3)}"
        )

    def test_tail_mass_interval_is_nondegenerate(self):
        """The whole point: the governance lever gets an error bar."""
        from beta_swarm.inference.proxy_posterior import posterior_tail_mass

        obs, outcomes = _synthetic_design(n=400, seed=6)
        post = ProxyPosterior(design_from_observables(obs, outcomes))
        rng = np.random.default_rng(1)
        res = hmc.sample(
            post, init=post.dispersed_inits(2, rng),
            n_draws=300, n_warmup=400, n_chains=2, seed=21,
        )
        tm = posterior_tail_mass(res.draws, obs[:25], tau=0.4, max_draws=100)
        assert tm.shape == (100, 25)
        assert np.all((tm >= 0.0) & (tm <= 1.0)), "p must stay in [0, 1]"

        # Uncertainty is *not* uniform across interactions, and asserting on the
        # median hides that. Most interactions are saturated — tail mass pinned
        # near 0 or 1, where no plausible parameter value changes the call, so
        # the spread is ~1e-10. The uncertainty concentrates on the borderline
        # cases, which are exactly the ones where a threshold call is close.
        # That concentration is the argument for carrying a posterior at all,
        # so it is what this test pins down.
        spread = tm.max(axis=0) - tm.min(axis=0)
        assert spread.max() > 0.05, (
            f"no interaction has materially uncertain tail mass "
            f"(max spread {spread.max():.2g}); the posterior is adding nothing"
        )
        assert np.mean(spread > 0.01) >= 0.1, (
            f"only {np.mean(spread > 0.01):.0%} of interactions carry meaningful "
            f"tail-mass uncertainty"
        )

    def test_tail_mass_uncertainty_concentrates_on_borderline_cases(self):
        """Spread must track distance from the threshold, not be noise."""
        from beta_swarm.inference.proxy_posterior import posterior_tail_mass

        obs, outcomes = _synthetic_design(n=400, seed=6)
        post = ProxyPosterior(design_from_observables(obs, outcomes))
        rng = np.random.default_rng(1)
        res = hmc.sample(
            post, init=post.dispersed_inits(2, rng),
            n_draws=300, n_warmup=400, n_chains=2, seed=21,
        )
        subset = obs[:60]
        tm = posterior_tail_mass(res.draws, subset, tau=0.4, max_draws=100)
        spread = tm.max(axis=0) - tm.min(axis=0)
        # Distance of the posterior-median tail mass from the 0.5 decision line.
        distance = np.abs(np.median(tm, axis=0) - 0.5)
        # Negative correlation: the closer to the line, the wider the interval.
        r = np.corrcoef(distance, spread)[0, 1]
        assert r < -0.3, f"uncertainty does not track borderline-ness (r={r:.2f})"
